# Part 1 Factorial with inner cache

In [5]:
def factorial(n, cache = {}):
    if(n==0): return 1
    #print(cache)
    if n in cache:
        return cache[n]
    else:
        cache[n] = n*factorial(n-1)
        return cache[n]

# Part 2

In [6]:
class X:
    def __init__(self,x):
        self.x = x
    def f1 (self):
        return 2*self.x
    def f2 (self):
        return 3*self.x
    def f3 (self):
        return 4*self.x

def class_decomposer (obj):
    dec = {}
    methods = [method for method in obj.__class__.__dict__.keys() if not method.startswith('__')]
    for i in methods:
        dec[i] = obj.__getattribute__(i)()
    return dec

obje = X(5)
print(class_decomposer(obje))

{'f1': 10, 'f2': 15, 'f3': 20}


# Part3

In [7]:
import numpy as np

def rotate(matrix):
    """
        Rotates matrix by 90 degrees anticlockwise...
        
        (The relation of rotation is congruent to transposition and reversing rows)
    """
    matrix = np.array(matrix)
    rotated = matrix.T
    rotated = np.flip(rotated,axis=0)
    return rotated

m = np.array([[1,2,3],[4,5,6],[7,8,9]])

    
class Rotation: 
    
    instance = {1: 0, 2: 0, 3: 0, 4: 0}
    
    def __new__ (cls, degree):
        if Rotation.instance[(degree/90)%4] == 0:
            Rotation.instance[(degree/90)%4]= object.__new__(Rotation)
            #print(Rotation.instance[(degree/90)%4])
        return Rotation.instance[(degree/90)%4]
    
    def __init__(self, degree):
        assert degree%90 == 0
        self.degree = degree
    
    def __call__(self,matrix):
        d = (self.degree/90)%4
        res = rotate(matrix)
        while d-1 != 0 :
            res = rotate(res)
            d -= 1
        return res
    
    def __str__(self):
        return "{}".format(self.__dir__ )
    

#Checking
r270 = Rotation(270)      
r450 = Rotation(450)
r90 = Rotation(90)
print(r450)
print(r90)
print(r270)
print('\n')
print(r450(m))

<built-in method __dir__ of Rotation object at 0x7f71f5fa9518>
<built-in method __dir__ of Rotation object at 0x7f71f5fa9518>
<built-in method __dir__ of Rotation object at 0x7f71f5fa9470>


[[3 6 9]
 [2 5 8]
 [1 4 7]]


# Part 4 Singleton

In [8]:
class Singleton: 
    instance = False
    
    def __new__ (cls):
        if not Singleton.instance:
            Singleton.instance = object.__new__(Singleton)
            return Singleton.instance
        else:
            return Singleton.instance
        
    
    def __init__(self):
        pass
    def __str__ (self):
        return "{}".format(self.__dir__ )
    
# Checking
s = Singleton()
d = Singleton()
e = Singleton()

print(s)
print(d)
print(e)

<built-in method __dir__ of Singleton object at 0x7f721c481f28>
<built-in method __dir__ of Singleton object at 0x7f721c481f28>
<built-in method __dir__ of Singleton object at 0x7f721c481f28>
